# Generated by Django 4.2 on 2024-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='Iam Ihsan, I recently completed my post graduation in field of MVoc Software development from university of calicut in 2023', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='personal_dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ihsan K', max_length=50)),
                ('age', models.IntegerField(default=22)),
                ('residence', models.CharField(default='Pandikkad, Malappuram ', max_length=100)),
                ('address', models.CharField(default='Pandikkad 676521, Malappuram, Kerala', max_length=200)),
                ('email', models.EmailField(default='ihsankpkd@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 7510719407, +91 7510719408', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='my_photo/')),
            ],
        ),
    ]
