# Generated by Django 4.2 on 2024-01-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snder_name', models.CharField(max_length=50)),
                ('sndr_mail', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
