# Generated by Django 4.2 on 2024-01-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_certificates_education_experience_projects_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='year',
            field=models.DateField(),
        ),
    ]
