# Generated by Django 4.2 on 2024-01-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_certificates_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
