# Generated by Django 4.2 on 2024-01-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_certificates_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='company',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
