# Generated by Django 4.2 on 2024-01-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_experience_start_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
