# Generated by Django 4.2 on 2024-01-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_education_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_dtl',
            name='phone',
            field=models.CharField(default='+91 7510719407, +91 7510719408', max_length=40),
        ),
    ]
