# Generated by Django 4.2 on 2024-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_personal_dtl_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_end_year',
            field=models.IntegerField(max_length=200),
        ),
    ]
