# Generated by Django 4.2 on 2024-01-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_education_start_end_year_education_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='start_end_year',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
