# Generated by Django 4.2 on 2024-01-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_experience_start_end_year_experience_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_year',
        ),
        migrations.AddField(
            model_name='experience',
            name='start_end_year',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
